language: python

python:
    # sets TRAVIS_PYTHON_VERSION
    - 3.6
    - 3.7
    - 3.8

os:
    - linux
    # - osx   # currently osx python projects are not supported in Travis

cache: pip

before_install:
    - git fetch --tags

install:
    - python setup.py install

before_script:
    # Make sure that interactive matplotlib backends work
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - sleep 3

script:
    - pytest
