language: python

python:
    # sets TRAVIS_PYTHON_VERSION
    - 3.6
    - 3.7
    - 3.8

os:
    - linux
    # - osx   # currently osx python projects are not supported in Travis

cache: pip

install:
    - pip install .

script:
    - pytest
