language: python

python:
    # sets TRAVIS_PYTHON_VERSION
    - 3.6

os:
    - linux
    # - osx   # currently osx python projects are not supported in Travis

cache: pip

install:
    - python setup.py install

script:
    - pytest
