package:
  name: indexedconv
  version: "0.1.0a0"

source:
  git_rev: installation
  git_url: https://github.com/IndexedConv/IndexedConv.git

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - pytorch
    - numpy
    - matplotlib
    - tensorboardx

test:
  imports:
  -

about:
  home: https://github.com/IndexedConv/IndexedConv
  license: MIT
  license_file: LICENSE